apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: safety-demo
  labels:
    app: safety-web
spec:
  type: LoadBalancer
  selector:
    app: safety-web
  ports:
    - name: http
      port: 80
      targetPort: 3001
